DataPlayGround/DataPlayGround/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^chatroom/', include('chatroom.urls')),
    url(r'^linreg/', include('linreg.urls')),
]

DataPlayGround/chatroom/urls.py
from django.conf.urls import url
from . import views

app_name = "chatroom"

urlpatterns = [
    #/chatroom/
    url(r'^$', views.index, name = "index"),
]

DataPlayGround/users/urls.py
from django.conf.urls import url
from . import views

app_name = "users"

urlpatterns = [
    #/users
    url(r'^$', views.index, name = "index"),

    #/users/base
    url(r'^base/$', views.base, name = "base"),

    #/users/login_user
    url(r'^login_user/$', views.login_user, name='login_user'),

    #/users/logout_user
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    #users/user_home
    url(r'^user_home/$', views.user_home, name='user_home')
]

DataPlayGround/chatroom/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.core.urlresolvers import reverse


# Create your models here.
class ChatRoom(models.Model):
    room_name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active =  models.BooleanField(default=False)

    def __str__(self):
        return self.room_name

class ChatMessage(models.Model):
    chat_room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=500)
    created_by = models.ForeignKey(User, default=1)

    def __str__(self):
        return self.chat_room.room_name + '-'+self.created_by.username+'-'+self.created_at.strftime('%H:%M %m/%d/%Y')

DataPlayGround/users/models.py
from django.db import models

# Create your models here.

DataPlayGround/users/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

DataPlayGround/chatroom/views.py
from django.views.generic import View
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login,logout
# Create your views here.

def index(request):
    if not request.user.is_authenticated():
        #return render(request, "users/loginform.html")
        return redirect("users:login_user")
    else:
        return render(request, "chatroom/index.html")

DataPlayGround/users/views.py
from django.views.generic import View
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.contrib.auth import authenticate
from django.contrib.auth import login,logout
from .forms import UserForm
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .serializers import UserSerializer
from django.contrib.auth.models import User
# Create your views here.


def index(request):
    return render(request, "users/loginform.html")

def base(request):
    return render(request, "base.html")


@api_view(['POST'])
def create_auth(request):
    serialized = UserSerializer(data=request.DATA)
    if serialized.is_valid():
        User.objects.create_user(
            serialized.init_data['email'],
            serialized.init_data['username'],
            serialized.init_data['password']
        )
        return Response(serialized.data, status=status.HTTP_201_CREATED)
    else:
        return Response(serialized._errors, status=status.HTTP_400_BAD_REQUEST)



def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user);
                #return render(request, 'users/userpage.html')
                return redirect('users:user_home')
            else:
                return render(request, 'users/loginform.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'users/loginform.html', {'error_message': 'Invalid login'})

    if not request.user.is_authenticated():
        return render(request, 'users/loginform.html')
    else:
        return redirect('users:user_home')
        #return render(request, 'users/userpage.html')

def logout_user(request):
    logout(request)
    return render(request, 'users/loginform.html')

def user_home(request):
    if not request.user.is_authenticated():
        return redirect("users:login_user")
    else:
        return render(request, 'users/userpage.html')

DataPlayGround/chatroom/templates/chatroom/index.html
{% extends "base.html" %}
{% load staticfiles%}
{% load render_bundle from webpack_loader %}
<script src="https://use.fontawesome.com/45e03a14ce.js"></script>

{% block body %}
    <style>
            #custom-search-input {
            background: #e8e6e7 none repeat scroll 0 0;
            margin: 0;
            padding: 10px;
        }
            #custom-search-input .search-query {
            background: #fff none repeat scroll 0 0 !important;
            border-radius: 4px;
            height: 33px;
            margin-bottom: 0;
            padding-left: 7px;
            padding-right: 7px;
        }
            #custom-search-input button {
            background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
            border: 0 none;
            border-radius: 3px;
            color: #666666;
            left: auto;
            margin-bottom: 0;
            margin-top: 7px;
            padding: 2px 5px;
            position: absolute;
            right: 0;
            z-index: 9999;
        }
            .search-query:focus + button {
            z-index: 3;
        }
            .all_conversation button {
            background: #f5f3f3 none repeat scroll 0 0;
            border: 1px solid #dddddd;
            height: 38px;
            text-align: left;
            width: 100%;
        }
            .all_conversation i {
            background: #e9e7e8 none repeat scroll 0 0;
            border-radius: 100px;
            color: #636363;
            font-size: 17px;
            height: 30px;
            line-height: 30px;
            text-align: center;
            width: 30px;
        }
            .all_conversation .caret {
            bottom: 0;
            margin: auto;
            position: absolute;
            right: 15px;
            top: 0;
        }
            .all_conversation .dropdown-menu {
            background: #f5f3f3 none repeat scroll 0 0;
            border-radius: 0;
            margin-top: 0;
            padding: 0;
            width: 100%;
        }
            .all_conversation ul li {
            border-bottom: 1px solid #dddddd;
            line-height: normal;
            width: 100%;
        }
            .all_conversation ul li a:hover {
            background: #dddddd none repeat scroll 0 0;
            color:#333;
        }
            .all_conversation ul li a {
            color: #333;
            line-height: 30px;
            padding: 3px 20px;
        }
            .member_list .chat-body {
            margin-left: 47px;
            margin-top: 0;
        }
            .top_nav {
            overflow: visible;
        }
            .member_list .contact_sec {
            margin-top: 3px;
        }
            .member_list li {
            padding: 6px;
        }
            .member_list ul {
            border: 1px solid #dddddd;
        }
            .chat-img img {
            height: 34px;
            width: 34px;
        }
            .member_list li {
            border-bottom: 1px solid #dddddd;
            padding: 6px;
        }
            .member_list li:last-child {
            border-bottom:none;
        }
            .member_list {
            height: 455px;
            overflow-x: hidden;
            overflow-y: auto;
            border: 1px solid #DDDDDD;
        }
            .sub_menu_ {
            background: #e8e6e7 none repeat scroll 0 0;
            left: 100%;
            max-width: 233px;
            position: absolute;
            width: 100%;
        }
            .sub_menu_ {
            background: #f5f3f3 none repeat scroll 0 0;
            border: 1px solid rgba(0, 0, 0, 0.15);
            display: none;
            left: 100%;
            margin-left: 0;
            max-width: 233px;
            position: absolute;
            top: 0;
            width: 100%;
        }
            .all_conversation ul li:hover .sub_menu_ {
            display: block;
        }
            .new_message_head button {
            background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
            border: medium none;
        }
            .new_message_head {
            background: #f5f3f3 none repeat scroll 0 0;
            float: left;
            font-size: 13px;
            font-weight: 600;
            padding: 18px 10px;
            width: 100%;
        }
            .message_section {
            border: 1px solid #DDDDDD;
        }
            .chat_area {
            float: left;
            height: 300px;
            overflow-x: hidden;
            overflow-y: auto;
            width: 100%;
        }
            .chat_area li {
            padding: 14px 14px 0;
        }
            .chat_area li .chat-img1 img {
            height: 40px;
            width: 40px;
        }
            .chat_area .chat-body1 {
            margin-left: 50px;
        }
            .chat-body1 p {
            background: #fbf9fa none repeat scroll 0 0;
            padding: 10px;
        }
            .chat_area .admin_chat .chat-body1 {
            margin-left: 0;
            margin-right: 50px;
        }
            .chat_area li:last-child {
            padding-bottom: 10px;
        }
            .message_write {
            background: #f5f3f3 none repeat scroll 0 0;
            float: left;
            padding: 15px;
            width: 100%;
        }

            .message_write textarea.form-control {
            height: 70px;
            padding: 10px;
            resize: vertical;
        }
            .chat_bottom {
            float: left;
            margin-top: 13px;
            width: 100%;
        }
            .upload_btn {
            color: #777777;
        }
            .sub_menu_ > li a, .sub_menu_ > li {
            float: left;
            width:100%;
        }
            .member_list li:hover {
            background: #428bca none repeat scroll 0 0;
            color: #fff;
            cursor:pointer;
        }
            .uname-font{
                {% comment %}text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;{% endcomment %}
        }
    </style>

    <div id="" class="container-fluid" style="align : center;">
        <div>
            <div class="main_section">
                <div class="container">
                    <div class="chat_container">
                        <div class="col-sm-3 chat_sidebar">
                            <div class="row">
                                <div class="member_list">
                                    <ul class="list-unstyled" id = 'chat_lobby'>

                                    </ul>
                                </div></div>
                            <div class = "fluid-container">
                                <div class="row">
                                    <button class="btn btn-block btn-primary" style="height: 50px; border-radius: 0px">
                                        Add Room
                                    </button>
                                </div>
                            </div>
                        </div>
                        <!--chat_sidebar-->


                        <div class="col-sm-9 message_section">
                            <div class="row">
                                <div class="new_message_head">
                                    <div class="pull-left" id="room_title_container"><button><i class="fa fa-plus-square-o" aria-hidden="true"></i>New Message</button></div><div class="pull-right"><div class="dropdown">
                                </div></div>
                                </div><!--new_message_head-->

                                <div class="chat_area">
                                    <ul class="list-unstyled" id="message_container">
                                    </ul>
                                </div><!--chat_area-->
                                <div class="message_write" id="input_container">
                                    <textarea class="form-control" placeholder="type a message"></textarea>
                                    <div class="clearfix"></div>
                                    <div class="chat_bottom">
                                        <a href="#" class="pull-right btn btn-success">
                                            Send</a>
                                    </div>
                                </div>
                            </div>
                        </div> <!--message_section-->
                    </div>
                </div>
            </div>
        </div>
        {% render_bundle 'chatroom' %}
    </div>
{% endblock %}

DataPlayGround/templates/base.html
<!DOCTYPE html>

<!--Loads the path to your static files-->
{% load render_bundle from webpack_loader %}
{% load staticfiles%}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
<link rel="stylesheet" type="text/css" href="{% static "style.css" %}"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src ="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src ="{% static "react.js" %}"></script>
<script type="text/javascript" src ={% static "react-dom.js" %}></script>
<script type="text/javascript" src ={% static "browser.min.js" %}></script>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Data Playground</title>
    <div class="container-fluid page-header text-center" style="margin-top: auto; margin-bottom: 0px; padding-bottom: 0px; border-bottom: 0px" >
        <h2>DataPlayground</h2>
      <p>Created By Gagan Tunuguntla</p>
    </div>
    <nav class="navbar navbar-default" style="padding-top: 0; border:0px">
      <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
          <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-left">
                <li class="{% if 'users' in request.path %}active{% endif %}"><a href="{% url 'users:user_home' %}">Home</a></li>
                <li class="{% if 'chatroom' in request.path %}active{% endif %}"><a href="{% url 'chatroom:index' %}">Chatroom</a></li>
                {% comment %}<li class="{% if 'linreg' in request.path %}active{% endif %}"><a href="{% url 'linreg:index' %}">Linear Regression</a></li>
                <li><a href="#">Logistic Regression</a></li>{% endcomment %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li class="">
                        <a href="{% url 'users:login_user' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden = "true"></span>&nbsp;
                            {{ request.user }}
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'users:logout_user' %}">
                            <span class="glyphicon glyphicon-log-out" aria-hidden = "true"></span>&nbsp;
                            Logout
                        </a>
                    </li>
                {% else %}
                    <li class="">
                        <a href="{% url 'users:index' %}">
                            <span class="glyphicon glyphicon-log-in" aria-hidden = "true"></span>&nbsp;
                            Login
                        </a>
                    </li>
                {% endif %}
            </ul>
          </div>
      </div>
    </nav>

</head>
<div id ='{{ request.session.session_key }}'>

</div>
<body>
    {% block body %}{% comment %}
        <div class = "container-fluid text-center">
            <h1>This is an empty template please overide the body block </h1>
        </div>{% endcomment %}
    {% endblock %}
</body>
</html>

DataPlayGround/users/templates/users/loginform.html
{% extends "base.html" %}
{% load staticfiles%}

<script src="{% static 'users/index.js' %}"></script>
{% block body %}
    <style>
        .login-container  {
          {% comment %}padding: 40px;{% endcomment %}
          min-height: 400px;
          max-width:600px;
          margin: auto;
          align : center;
        }
        .panel-login {
            border-color: #ccc;
            align : center;
            -webkit-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
            -moz-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
            box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
        }
        .panel-login>.panel-heading {
            color: #00415d;
            background-color: #fff;
            border-color: #fff;
            text-align:center;
            font-size: 1.4em;/
        }
        .panel-login>.panel-heading a{
            text-decoration: none;
            color: #666;
            font-weight: bold;
            font-size: 14px;
            -webkit-transition: all 0.1s linear;
            -moz-transition: all 0.1s linear;
            transition: all 0.1s linear;
        }
        .panel-login>.panel-heading a.active{
            color: #029f5b;
            font-size: 14px;
        }

        .panel-login>.panel-heading hr{
            margin-top: 10px;
            margin-bottom: 0px;
            clear: both;
            border: 0;
            height: 1px;
            background-image: -webkit-linear-gradient(left,rgba(0, 0, 0, 0),rgba(0, 0, 0, 0.15),rgba(0, 0, 0, 0));
            background-image: -moz-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
            background-image: -ms-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
            background-image: -o-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
        }
        .panel-login input[type="text"],.panel-login input[type="email"],.panel-login input[type="password"] {
            height: 45px;
            border: 1px solid #ddd;
            font-size: 16px;
            -webkit-transition: all 0.1s linear;
            -moz-transition: all 0.1s linear;
            transition: all 0.1s linear;
        }
        .panel-login input:hover,
        .panel-login input:focus {
            outline:none;
            -webkit-box-shadow: none;
            -moz-box-shadow: none;
            box-shadow: none;
            border-color: #ccc;
        }
        .btn-login {
            background-color: #59B2E0;
            outline: none;
            color: #fff;
            font-size: 14px;
            height: auto;
            font-weight: normal;
            padding: 14px 0;
            text-transform: uppercase;
            border-color: #59B2E6;
        }
        .btn-login:hover,
        .btn-login:focus {
            color: #fff;
            background-color: #53A3CD;
            border-color: #53A3CD;
        }
        .forgot-password {
            text-decoration: underline;
            color: #888;
        }
        .forgot-password:hover,
        .forgot-password:focus {
            text-decoration: underline;
            color: #666;
        }

        .btn-register {
            background-color: #1CB94E;
            outline: none;
            color: #fff;
            font-size: 14px;
            height: auto;
            font-weight: normal;
            padding: 14px 0;
            text-transform: uppercase;
            border-color: #1CB94A;
        }
        .btn-register:hover,
        .btn-register:focus {
            color: #fff;
            background-color: #1CA347;
            border-color: #1CA347;
        }

        @media(max-width: 400px) {
            .panel-login>.panel-heading a.active {
                font-size: 10px;
            }
            .panel-login>.panel-heading a{
                text-decoration: none;
                color: #666;
                font-weight: bold;
                font-size: 10px;
                -webkit-transition: all 0.1s linear;
                -moz-transition: all 0.1s linear;
                transition: all 0.1s linear;
            }
            .panel-login input[type="text"],.panel-login input[type="email"],.panel-login input[type="password"] {
                height: 30px;
                border: 1px solid #ddd;
                font-size: 10px;
                -webkit-transition: all 0.1s linear;
                -moz-transition: all 0.1s linear;
                transition: all 0.1s linear;
            }
            .btn-register, .btn-login, .remember-text {
                font-size: 10px;
            }
        }

    </style>
    <div class="container-fluid" style="align : center;">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-login">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-6">
                                <a href="#" class="active" id="login-form-link">Login</a>
                            </div>
                            <div class="col-xs-6">
                                <a href="#" id="register-form-link">Register</a>
                            </div>
                        </div>
                        <hr>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <form id="login-form" action="{% url 'users:login_user'%}" method="post" enctype="multipart/form-data" role="form" style="display: block;">
                                    {% csrf_token %}
                                    {% if error_message %}
                                        <p class="bg-danger" style="text-align: center"><strong>{{ error_message }}</strong></p>
                                    {% endif %}
                                    <div class="form-group">
                                        <input type="text" name="username" id="id_username" tabindex="1" class="form-control" placeholder="Username" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" id="id_password" tabindex="2" class="form-control" placeholder="Password">
                                    </div>
                                    <div class="form-group text-center remember-text">
                                        <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                                        <label for="remember"> Remember Me</label>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-6 col-sm-offset-3">
                                                <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
                                            </div>
                                        </div>
                                    </div>
                                    {% comment %}<div class="form-group">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="text-center">
                                                    <a href="http://phpoll.com/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>{% endcomment %}
                                </form>
                                <form id="register-form" action="#" method="post" role="form" style="display: none;">
                                    <div class="form-group">
                                        <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-6 col-sm-offset-3">
                                                <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(function() {

            $('#login-form-link').click(function(e) {
                $("#login-form").delay(100).fadeIn(100);
                $("#register-form").fadeOut(100);
                $('#register-form-link').removeClass('active');
                $(this).addClass('active');
                e.preventDefault();
            });
            $('#register-form-link').click(function(e) {
                $("#register-form").delay(100).fadeIn(100);
                $("#login-form").fadeOut(100);
                $('#login-form-link').removeClass('active');
                $(this).addClass('active');
                e.preventDefault();
            });

        });

    </script>
{% endblock %}

DataPlayGround/users/templates/users/userpage.html
{% extends "base.html" %}
{% load staticfiles%}

<script src="{% static 'users/index.js' %}"></script>
{% block body %}
    <style>

    </style>
    <div class="container-fluid" style="align : center;">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {{ request.user}}
            </div>
        </div>
    </div>

    <script>
        $(function() {

            $('#login-form-link').click(function(e) {
                $("#login-form").delay(100).fadeIn(100);
                $("#register-form").fadeOut(100);
                $('#register-form-link').removeClass('active');
                $(this).addClass('active');
                e.preventDefault();
            });
            $('#register-form-link').click(function(e) {
                $("#register-form").delay(100).fadeIn(100);
                $("#login-form").fadeOut(100);
                $('#login-form-link').removeClass('active');
                $(this).addClass('active');
                e.preventDefault();
            });

        });

    </script>
{% endblock %}